#define _HAS_THINGSPEAK
#define _HAS_ETHERNET
//#define _HAS_WIFI
//#define _HAS_GSM
#define _HAS_DHT
#define _HAS_DALLAS
#define _HAS_PUMP_RELAY
#define _HAS_LAMP_RELAY
#define _HAS_PH
#define _HAS_EC
#define _HAS_VBATT
